<p>
    Version <?php echo WPC_CLIENT_LITE_VER ?>
</p>
<h3>Privacy Policy</h3>
<p><a href="http://www.wp-client.com/">WP-Client.com</a>&nbsp;will never sell any information associated with your account. Server logs are maintained for hit-tracking purposes and your IP address will be recorded.</p>
<p><a href="http://www.wp-client.com/">WP-Client.com</a>&nbsp;was developed with security and privacy as its highest priority, however, it is not responsible should information get exposed through hacker exploitation or otherwise.</p>
<h3>Terms of Service</h3>
<p>You agree that the owners of this web site (<a href="http://www.wp-client.com/">WP-Client.com</a>) exclusively reserve the right and may, at any time and without notice and any liability to you, modify or discontinue this web site and its services or delete the data you provide, whether temporarily or permanently. We (<a href="http://www.wp-client.com/">WP-Client.com</a>) shall have no liability for the timeliness, deletion, failure to store, inaccuracy, or improper delivery of any data or information.</p>
<p>The use of this site and/or application is provided "AS IS" and NO guarantee, implied or express, is provided should there be any error, data loss, breach of privacy or any other event causing any malfunction whatsoever. It is up to the user to back-up any information input into the <a href="http://www.wp-client.com/">WP-Client.com</a>&nbsp;application and service may stop without prior warning. Any account may be removed at any time for any reason.</p>
<p>You assume total responsibility and risk for your use of this Service; use at your own risk.</p>
<p>By using this service, you acknowledge you are at least 14 years old.</p>
<h3>DISCLAIMER OF WARRANTIES</h3>
<p>YOU UNDERSTAND AND AGREE THAT YOUR USE OF THIS WEB SITE AND ANY SERVICES OR CONTENT PROVIDED (THE SERVICE) IS MADE AVAILABLE AND PROVIDED TO YOU AT YOUR OWN RISK. IT IS PROVIDED TO YOU AS IS AND WE EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, IMPLIED OR EXPRESS, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>
<p><a href="http://www.wp-client.com/">WP-Client.com</a>&nbsp;MAKES NO WARRANTY, IMPLIED OR EXPRESS, THAT ANY PART OF THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, VIRUS-FREE, TIMELY, SECURE, ACCURATE, RELIABLE, OF ANY QUALITY, NOR THAT ANY CONTENT IS SAFE IN ANY MANNER FOR DOWNLOAD. YOU UNDERSTAND AND AGREE THAT NEITHER US NOR ANY PARTICIPANT IN THE SERVICE PROVIDES PROFESSIONAL ADVICE OF ANY KIND AND THAT USE OF SUCH ADVICE OR ANY OTHER INFORMATION IS SOLELY AT YOUR OWN RISK AND WITHOUT OUR LIABILITY OF ANY KIND.</p>
<p>Some jurisdictions may not allow disclaimers of implied warranties and the above disclaimer may not apply to you only as it relates to implied warranties.</p>
<p><a href="http://www.wp-client.com/">WP-Client.com</a>&nbsp;makes no guarantee of availability of service and reserves the right to change, withdraw, suspend, or discontinue any functionality or feature of the <a href="http://www.wp-client.com/">WP-Client.com</a>&nbsp;service.</p>
<h3>LIMITATION OF LIABILITY</h3>
<p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT WE SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL, INDICENTAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSS (EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM OR ARISING OUT OF (I) THE USE OF OR THE INABILITY TO USE THE SERVICE, (II) THE COST TO OBTAIN SUBSTITUTE GOODS AND/OR SERVICES RESULTING FROM ANY TRANSACTION ENTERED INTO ON THROUGH THE SERVICE, (III) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR DATA TRANSMISSIONS, (IV) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SERVICE, OR (V) ANY OTHER MATTER RELATING TO THE SERVICE.</p>
<h3>Third Party Services</h3>
<p>Goods and services of third parties may be mentioned and/or made available on or through this web site. Representations made regarding products and services provided by third parties are governed by the policies and representations made by these third parties. We shall not be liable for or responsible in any manner for any of your dealings or interaction with third parties.</p>

